### PR TITLE
Python 2 and Python 3 compatibility

### LINKED ISSUE #2: Python 3 support
Hello,

it will be nice if you could add Python 3 support
(same code for Python 2 and Python 3)

Kind regards

### PR DESCRIPTION
**Pull request by femtotrader**
Try to fix https://github.com/Weswit/Lightstreamer-example-StockList-client-python/issues/2

### CODE REVIEW

**Comment by gfinocchiaro** [comment]
Hi femtotrader,

thanks for your contribution. I am reviewing your changes and I will let you know as soon as possible.

Gianluca

**Comment by femtotrader** [comment]
Don't merge... see https://github.com/Weswit/Lightstreamer-example-StockList-client-python/issues/2

**Comment by gfinocchiaro** [comment]
No merge, just checking...

Demo does not work with your proposed changes: Import error: No module named 'six'.

**Comment by gfinocchiaro** [comment]
Oops... I have to install six package...

**Comment by gfinocchiaro** [comment]
After I've installed 'six' module (already installed in Python34), application is indefinitely waiting for establishing the connection.

**Comment by femtotrader** [comment]
That's exactly my problem and that's why porting your code to Python 3 is not so trivial.

**Comment by gfinocchiaro** [comment]
It works well in Python 2 if you update compat.py as follows:
from
`from urllib2 import urlopen as _urlopen`
to:
`from urllib import urlopen as _urlopen`.

Anyway, with Python3, the problem is how http response is managed, since the urlopen method returns an HTTPResponse object, which does not have any "readline"() method.
You can use "read", but remember that Lightstreamer works with http streaming, so you cannot read the whole response. You should split the response, looking for "\r\n" in order to parse command response...

**Comment by femtotrader** [comment]
You can also consider using requests

http://www.python-requests.org/

**Comment by femtotrader** [comment]
http://www.python-requests.org/en/latest/user/quickstart/#response-content

> In the rare case that you’d like to get the raw socket response from the server, you can access r.raw. If you want to do this, make sure you set stream=True in your initial request. Once you do, you can do this:

**Comment by femtotrader** [comment]
Any news about Python 3 support ?

**Comment by femtotrader** [comment]
Maybe you might try to use requests with Python 2 first and after move to Python 3.

**Comment by gfinocchiaro** [comment]
I'll let you know, I'm working on it.

**Comment by gfinocchiaro** [comment]
Demo now works with both versions of Python. Let me know.

**Comment by femtotrader** [comment]
Thanks a lot

**Pull request closed without merging**
